### ISSUE TITLE
Embedding and auto updating

### ISSUE THREAD

**Issue by drelatgithub** [FlorianRappl/Chocolatey-Julia#5]
Thanks for wrapping up this package!

Currently Julia has entered 1.0.1, but this slightly newer version is not yet available in chocolatey. Instead of requesting an update or creating a PR for this package, I am wondering if it is possible to migrate this package to [chocolatey/chocolatey-coreteampackages](https://github.com/chocolatey/chocolatey-coreteampackages), with embedding executable and auto update configurations. Several reasons that I think this could be appropriate are
- [With the Auto Updater (AU)](https://chocolatey.org/docs/automatic-packages), it is possible write the script only once, and when new versions are released, simply running the update script can update all the associated information (including checksum) of the package.
- The repository chocolatey/chocolatey-coreteampackages has configured a dedicated appveyor service that can frequently check for update, run updating scripts for all outdated packages, and push the updated packages to chocolatey, which virtually freed work for maintaining the package.
- Julia is MIT licensed, which allows redistribution of the software given the license information is included, which make embedding the executable possible. Embedding an executable happens during auto update, and after an executable is included in the package, the package installing process will be independent of the julialang download website.

To do this, one can follow the documentation of creating AU scripts, and then submit a PR to the chocolatey-coreteampackages repository. I can also help with all these work (since I've done it before) and keep you as the package maintainer, if you think that is fine.

Of course, however, the decision is up to you! But I would really like to hear your idea about this. Thanks!

**Comment by FlorianRappl** [comment]
Hi @drelatgithub - thanks a lot for the message and sharing your thoughts. I think going for the community repo sounds great and would be the ideal way forward.

The only thing that is still unclear what I need to / should do to perform the migration. How can I help? Obviously, you are more experienced than me in that matter. E.g., what collaboration rights on this repo be useful to you?

Let's make it happen! 🍻

**Comment by drelatgithub** [comment]
Thanks for the interest!

Currently I am copy-pasting your work into my fork of coreteampackages, and I will make changes on top of that. The changes could be tracked [here](https://github.com/chocolatey/chocolatey-coreteampackages/compare/master...drelatgithub:master).

And I think when we both think it is okay, we can create a PR to the main repository. 🍻

**Comment by FlorianRappl** [comment]
Awesome - great job and thanksf or inviting me to collaborate!

**Comment by drelatgithub** [comment]
Currently I've already finished most part of the modification, and you can view them using the link above. Several notable changes are:
- I've added chocolatey to the list of maintainers following the guideline. Also I've shamelessly added myself as the maintainer. (So currently there are in total 3 maintainers for this package, but if you do not think it is good, you can remove me from the list, but chocolatey has to stay in the list.)
- All the places with "to be replaced" will be replaced by the auto updater during an update. I've tested them locally and hopefully they will work.
- The content of the `README.md` will be automatically copied as the description of the package. Currently, however, `README.md` is *not* PR ready. There is a requirement on the readme that a list of `## Features` needs to be added. I've already added the features section, but may I use your help in editing the content of the list of features?

Thanks!

**Comment by drelatgithub** [comment]
I've copy-pasted the features section from the Wikipedia, and the tests passed on my machine and I guess all is done for preparing a pull request to migrate the package.

I'll submit the pull request as long as you think it's good.

**Comment by FlorianRappl** [comment]
Briefly looked over it - I think it looks fantastic (and thanks for doing the maintainer change / addition - I would have otherwise proposed that).

Let's say the PR is there and accepted is there anything I need to do for making the community packages work / i.e., change of ownership?

**Comment by drelatgithub** [comment]
Following the [migration guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Package-migration-process) it seems that a PR to delete the current package is needed, but I guess since this is a one-package repo anyway, it could be deleted or archived as a whole. So I think I'll submit a PR to this repository to delete the original code if only it is required by the reviewer there.

https://github.com/chocolatey/chocolatey-coreteampackages/pull/1133

**Comment by drelatgithub** [comment]
Thanks a lot for the help and [the package is now updated](https://chocolatey.org/packages/Julia)! Hopefully the auto-updater will save us the work on maintaining in the future.

As for this repository, since the content is no longer maintained, I would suggest to archive it so that it would be in an inactive state while retaining all the history. But of course I'll leave this decision up to you!

**Comment by FlorianRappl** [comment]
Good point - will be archived!

Thanks for the swift collaboration. Really enjoyed it! :beers:
